# Generated by Django 5.2.15 on 2026-08-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_channel_lookup_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(blank=True, help_text='Profile picture URL from the OIDC provider, if any.', max_length=500, null=True, verbose_name='picture'),
        ),
    ]
